# This is a config for E2B sandbox template.
# You can use template ID (f11ler9fxcjdofsvcpa4) or template name (vibe-nextjs-test-ii) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-test-ii") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-ii") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-ii')

team_id = "d5519aca-655f-49c7-809c-c5ab04887986"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-ii"
template_id = "f11ler9fxcjdofsvcpa4"
